/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statement.analyzer;

import org.junit.jupiter.api.Test;

class MainApplicationTest {
    @Test
    public static void main(String[] args) {
        
    }
}
