/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banktransaction;

import java.io.IOException;

import banktransaction.service.BankStatementAnalyzer;
import banktransaction.util.BankStatementCSVParser;
import banktransaction.util.BankStatementParser;

public class App {
    
    public static void main(String[] args) throws IOException {
        final String fileName = args[0];
        final BankStatementParser bankStatementParser = new BankStatementCSVParser();
        final BankStatementAnalyzer bankStatementAnalyzer = new BankStatementAnalyzer();
        
        bankStatementAnalyzer.analyze(fileName, bankStatementParser);
    }
}
