name: CI-Quality

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x ./gradlew
      - run: ./gradlew tasks
      - run: ./gradlew clean check
      - run: ./gradlew assemble